apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: sandbox
spec:
  ports:
  - port: 41111
    protocol: TCP
    targetPort: 31111
  selector:
    app: techtrends
  type: ClusterIP
